name: Workflow testing
on:
  push:
    branches: 
      - master
env:
  VAR1: "VALUE1"
  VAR2: "VALUE2"
jobs:
  my_test1:
    runs-on: ubuntu-latest
    steps:
    - name: Print Hello World
      run: echo "Hello, World!"
    - name: Print env vars
      run: echo "Var1 is ${{ env.VAR1 }}"
