name: Deploy Flask App to AWS ElasticBeanstalk

on:
  push:
    branches:
      - master
env:
  AWS_PACKAGE_S3_BUCKET_NAME : "flask-ebs"
  EB_APPLICATION_NAME        : "Flask"
  EB_ENVIRONMENT_NAME        : "Flask-env"
  DEPLOY_PACKAGE             : "myflask-${{ github.sha }}.zip"
  AWS_REGION                 : "us-east-2"

jobs:
  CI_PART:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2
    
      - name: Create zip file
        run: zip -r ${{ env.DEPLOY_PACKAGE }} -x *.git*
           
      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws_access_key_id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region            : ${{ env.AWS_REGION }}
      
      
      - name: Copy zip to S3
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE }} s3://${{ env.AWS_PACKAGE_S3_BUCKET_NAME }}
  CD_PART:
    runs-on: ubuntu-latest   
    needs: [CI_PART]
    steps:
      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id     : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region            : ${{ env.AWS_REGION }}
      
      - name: Create EBS AppVersion
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.AWS_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE }}" --version-label "Version-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
     
      - name: Update EBS env
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Version-${{ github.sha}}"
      
      
      
      
      
