name: My-deployment-to-aws
env:
  EB_PACKAGE_S3_BUCKET_NAME: "My-flask-application-packages"
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIRONMENT_NAME: "Myflask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION: "us-east-2"
on:
  push:
     branches: 
       - master 
jobs: 
  my_ci_part:
    runs-on: [ubuntu-latest]
    steps:
    
    - name: Clone repo
      uses: actions/checkout@v1
    - name: Create zip package
      run: zip -r $ {{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
    - name: Configure access to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ AWS_REGION }}    
    - name: Copy to S3 Bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ EB_PACKAGE_S3_BUCKET_NAME }}/
    - name: Print message on success
      run: echo "Success! The CI part has finished."  
  my_cd_part:
    runs-on: [ubuntu-latest]
    needs: my_ci_part
    steps:
    - name: Configure access to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Create application on EB
      run: |
        aws elastibeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}", S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
        --version-label="version-${{ github.sha }}" \
        --description="CommitSHA-${{ github.sha }}"
    - name: Deploy application
      run: aws elastibeanstalk update-environment --environment-name  "${{env.EB_ENVIRONMENT_NAME}}" --version-label "$version-${{ github.sha }}"       
