name: My-deployment-to-AWS-Beanstalk
env:
  AWS_PACKAGE_S3_BUCKET_NAME: "hessor.bucket"
  EB_APPLICATION_NAME: "FlaskApp"
  EB_ENVIRONMENT_NAME: "Flaskapp-env"
  AWS_REGION: "us-east-2"
  DEPLOY_PACKAGE: "flask-app-${{ github.sha }}.zip"
on:
  push:
    branches:
    - master
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps:
    - name: Copy repo to container
      uses: actions/checkout@v1
    - name: Archive app files
      run: zip -r ${{ env.DEPLOY_PACKAGE }} ./ -x *.git*
    - name: Configure access to AWS 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Copy zip-archive to S3Bucket 
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE }} s3://${{ env.AWS_PACKAGE_S3_BUCKET_NAME }}
    - name: Message on success
      run: echo "Success! CI part has finished."

  my_cd_part:
    needs: [my_ci_part]
    runs-on: ubuntu-latest
    steps:
    - name: Configure access to AWS 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Create Beanstalk App 
      run: |
        aws elasticbeanstalk create-application-version \
        --application-name ${{ env.EB_APPLICATION_NAME }} \
        --source-bundle S3Bucket="${{ env.AWS_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE }}" \ 
        --version-label "Version-${{ github.sha }}" \
        --description "CommitSHA-${{ github.sha }}"
    - name: Update EN app env
      run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Version - ${{ github.sha}}"        
