name: My-Deployment-to-AWS
env: 
  EB_PACKAGE_S3_BUCKET_NAME: "my-flask-application-packages" 
  EB_APPLICATION_NAME: "MyFlask"
  EB_ENVIRONMENT_NAME: "Myflask-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-east-2"
on:
  push:
    branches: 
      - master
jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      - name: Check
        run: ls -al
      - name: Configure access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Copy Deploymnet packages to S3
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/
      - name: Print Message
        run: echo "OK! CI part finished!"
  my_cd_part:
    runs-on: [ubuntu-latest]
    needs: [my_ci_part]
    steps:
      - name: Configure access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Create new ElastivBeanstalk App
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label="Version-${{ github.sha }}" \
          --description "CommitSHA-${{ github.sha }}"
      - name: Deploy new App Version
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENVIRONMENT_NAME }} --version-label "Version-${{ github.sha }} "
